
[Main]
	#Replace Wither
	"替换凋灵" = true
	#Generate Opening Animation All
	"任意方式生成拥有开场动画" = true

[Attributes]

	[Attributes.Boss]
		#Boss Base Attribute Can Use Config
		"Boss基础属性可以被配置影响" = true
		#Boss Has Percentage Damage
		"Boss拥有百分比伤害" = true
		#Boss Has Damage Cap
		"Boss拥有限伤" = true
		#Boss Has Damage Cooldown Tick
		"Boss拥有无敌帧" = false

		[Attributes.Boss."War Wither"]
			#War Wither Boss Bar Color
			#Range: 0 ~ 6
			"战争凋零Boss血条颜色" = 1
			#War Wither Boss Bar Name Color
			#Range: > 0
			"战争凋零Boss血条名字颜色" = 3421236
			#[Boss] Max Health : 600.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Max Health" = 500.0
			#[Boss] Melee Damage : 20.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Melee Damage" = 55.0
			#[Boss] Armor : 4.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Armor" = 12.0
			#[Boss] Movement Speed : 0.60
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Movement Speed" = 0.7
			#[Boss] Flying Speed : 0.60
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Flying Speed" = 0.7
			#[Boss] Attack Knockback : 2.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Attack Knockback" = 3.0
			#[Boss] Knockback Resistance : 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Knockback Resistance" = 1.0
			#[Boss] Spell Normal Level : 3
			#Range: > 0
			"War Wither Spell Normal Level" = 3
			#[Boss] Attack Percentage : 5.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Attack Percentage" = 5.0
			#[Boss] Magic Attack Percentage : 5.0
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Magic Attack Percentage" = 1.0
			#[Boss] Damage Cap : 40
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Damage Cap" = 20.0
			#[Boss] Damage Cooldown Tick : 20
			#Range: 0.0 ~ 1.7976931348623157E308
			"War Wither Damage Cooldown Tick" = 20.0

